// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccountService exposes account management to the frontend. The heavy
 * lifting lives in internal/accounts; this layer adds the store handle and
 * broadcasts "accounts:changed" so every window refreshes its rail.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as accounts$0 from "./internal/accounts/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

export function AddAccount(input: accounts$0.AddInput): $CancellablePromise<store$0.Account> {
    return $Call.ByID(2297861020, input);
}

export function ListAccounts(): $CancellablePromise<store$0.Account[] | null> {
    return $Call.ByID(2760578426);
}

export function RemoveAccount(id: string): $CancellablePromise<void> {
    return $Call.ByID(2544074941, id);
}

/**
 * ReorderAccounts persists the drag-and-drop rail order (all account ids in
 * their new sequence).
 */
export function ReorderAccounts(ids: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(540797413, ids);
}

export function UpdateAccount(input: accounts$0.UpdateInput): $CancellablePromise<store$0.Account> {
    return $Call.ByID(592440522, input);
}
