// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIService binds the AI features to the frontend and, when the user opts
 * in, keeps list-row digests generated in the background after each sync.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ai$0 from "./internal/ai/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

export function ActionItems(accountID: string, threadID: string): $CancellablePromise<ai$0.ActionItem[] | null> {
    return $Call.ByID(1532129271, accountID, threadID);
}

export function ComposeInstructed(req: ai$0.ComposeRequest): $CancellablePromise<string> {
    return $Call.ByID(417289150, req);
}

export function DraftReply(accountID: string, threadID: string): $CancellablePromise<string> {
    return $Call.ByID(2892712478, accountID, threadID);
}

export function GetConfig(): $CancellablePromise<ai$0.Config> {
    return $Call.ByID(4188563059);
}

/**
 * MessageArtifacts bulk-fetches per-message AI outputs for list rendering
 * (kind: "msg-summary" digests or "triage" labels), keyed by message id.
 */
export function MessageArtifacts(kind: string, messageIDs: number[] | null): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(4178538501, kind, messageIDs);
}

export function Rewrite(text: string, tone: string): $CancellablePromise<string> {
    return $Call.ByID(2524614873, text, tone);
}

export function SetConfig(provider: string, model: string, listSummaries: boolean, apiKey: string): $CancellablePromise<void> {
    return $Call.ByID(833121423, provider, model, listSummaries, apiKey);
}

export function SuggestUnsubscribes(): $CancellablePromise<store$0.UnsubscribeCandidate[] | null> {
    return $Call.ByID(2153286933);
}

export function SummarizeThread(accountID: string, threadID: string): $CancellablePromise<string> {
    return $Call.ByID(2206037860, accountID, threadID);
}

export function Translate(text: string, language: string): $CancellablePromise<string> {
    return $Call.ByID(2432548167, text, language);
}

export function TriageInbox(accountID: string): $CancellablePromise<ai$0.TriageResult[] | null> {
    return $Call.ByID(48646713, accountID);
}
