// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIService binds the AI features to the frontend and, when the user opts
 * in, keeps list-row digests generated in the background after each sync.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ai$0 from "./internal/ai/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

/**
 * ActionItems re-extracts a thread's checklist and returns the persisted
 * rows (open first, done history kept).
 */
export function ActionItems(accountID: string, threadID: string): $CancellablePromise<store$0.ActionItemRow[] | null> {
    return $Call.ByID(1532129271, accountID, threadID);
}

export function ComposeInstructed(req: ai$0.ComposeRequest): $CancellablePromise<string> {
    return $Call.ByID(417289150, req);
}

export function DraftReply(accountID: string, threadID: string): $CancellablePromise<string> {
    return $Call.ByID(2892712478, accountID, threadID);
}

export function GetConfig(): $CancellablePromise<ai$0.Config> {
    return $Call.ByID(4188563059);
}

/**
 * ListActionItems returns a thread's saved checklist without re-extracting.
 */
export function ListActionItems(accountID: string, threadID: string): $CancellablePromise<store$0.ActionItemRow[] | null> {
    return $Call.ByID(297992639, accountID, threadID);
}

/**
 * ListModelRules returns the per-feature model overrides.
 */
export function ListModelRules(): $CancellablePromise<ai$0.ModelRule[] | null> {
    return $Call.ByID(2259369971);
}

/**
 * ListPrompts returns every AI instruction with its current override.
 */
export function ListPrompts(): $CancellablePromise<ai$0.PromptInfo[] | null> {
    return $Call.ByID(1613469218);
}

/**
 * MessageArtifacts bulk-fetches per-message AI outputs for list rendering
 * (kind: "msg-summary" digests or "triage" labels), keyed by message id.
 */
export function MessageArtifacts(kind: string, messageIDs: number[] | null): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(4178538501, kind, messageIDs);
}

export function Rewrite(text: string, tone: string): $CancellablePromise<string> {
    return $Call.ByID(2524614873, text, tone);
}

/**
 * SetActionItemDone toggles one checklist entry.
 */
export function SetActionItemDone(id: number, done: boolean): $CancellablePromise<void> {
    return $Call.ByID(3174599792, id, done);
}

export function SetConfig(provider: string, model: string, listSummaries: boolean, apiKey: string): $CancellablePromise<void> {
    return $Call.ByID(833121423, provider, model, listSummaries, apiKey);
}

/**
 * SetModelRule ties one AI feature to one model; empty provider clears it.
 */
export function SetModelRule(feature: string, provider: string, model: string): $CancellablePromise<void> {
    return $Call.ByID(3195257620, feature, provider, model);
}

/**
 * SetPrompt overrides one instruction; empty text resets to the default.
 */
export function SetPrompt(id: string, custom: string): $CancellablePromise<void> {
    return $Call.ByID(3495695763, id, custom);
}

export function SuggestUnsubscribes(): $CancellablePromise<store$0.UnsubscribeCandidate[] | null> {
    return $Call.ByID(2153286933);
}

export function SummarizeThread(accountID: string, threadID: string): $CancellablePromise<string> {
    return $Call.ByID(2206037860, accountID, threadID);
}

export function Translate(text: string, language: string): $CancellablePromise<string> {
    return $Call.ByID(2432548167, text, language);
}

export function TriageInbox(accountID: string): $CancellablePromise<ai$0.TriageResult[] | null> {
    return $Call.ByID(48646713, accountID);
}
