// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BootService owns backend startup. Everything the app needs before first
 * paint happens in ServiceStartup — today that is opening SQLite and running
 * migrations; keychain checks and cache warming join it in later phases. The
 * frontend splash gates on this via IsBackendReady / the "backend:ready"
 * event. Other services in this package reach the shared store through
 * BootService.st.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * BootError returns the startup failure message, empty when startup was clean.
 */
export function BootError(): $CancellablePromise<string> {
    return $Call.ByID(3542600309);
}

/**
 * IsBackendReady reports whether backend startup finished. The frontend calls
 * this before listening for "backend:ready" to avoid the missed-event race.
 */
export function IsBackendReady(): $CancellablePromise<boolean> {
    return $Call.ByID(907424186);
}
