// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LabelService is the UI surface for category labels: CRUD, manual
 * assignment, the AI batch classifier, and the auto-create toggle.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

export function AutoCreateEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(3642932025);
}

export function CreateLabel(label: store$0.Label): $CancellablePromise<store$0.Label> {
    return $Call.ByID(2329199471, label);
}

export function DeleteLabel(id: number): $CancellablePromise<void> {
    return $Call.ByID(1662860890, id);
}

/**
 * LabelInbox runs one AI classification batch over unlabeled inbox mail
 * and returns how many messages were labeled.
 */
export function LabelInbox(): $CancellablePromise<number> {
    return $Call.ByID(3725910933);
}

export function ListLabels(): $CancellablePromise<store$0.Label[] | null> {
    return $Call.ByID(2165279988);
}

export function ReorderLabels(ids: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(2255525541, ids);
}

export function SetAutoCreate(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1399156162, enabled);
}

/**
 * SetMessageLabel is the manual override — it wins over the classifier
 * permanently for that message.
 */
export function SetMessageLabel(messageID: number, labelID: number): $CancellablePromise<void> {
    return $Call.ByID(1289293650, messageID, labelID);
}

export function UpdateLabel(label: store$0.Label): $CancellablePromise<void> {
    return $Call.ByID(3859494644, label);
}
