// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MailService is the UI's read path onto local mail, plus the small write
 * operations reading implies (mark read). Heavier actions live in Phase 5.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

/**
 * Archive moves a message into the account's archive folder on the server.
 */
export function Archive(messageID: number): $CancellablePromise<void> {
    return $Call.ByID(1112366144, messageID);
}

/**
 * CountByRole counts messages in folders of one role (the Drafts badge).
 */
export function CountByRole(role: string): $CancellablePromise<number> {
    return $Call.ByID(2161049184, role);
}

export function GetMessageBody(messageID: number): $CancellablePromise<store$0.MessageBody> {
    return $Call.ByID(548725893, messageID);
}

export function GetThread(accountID: string, threadID: string): $CancellablePromise<store$0.Message[] | null> {
    return $Call.ByID(3829466066, accountID, threadID);
}

export function ListAttachments(messageID: number): $CancellablePromise<store$0.Attachment[] | null> {
    return $Call.ByID(600173696, messageID);
}

export function ListMessages(filter: store$0.ListFilter): $CancellablePromise<store$0.Message[] | null> {
    return $Call.ByID(3645670514, filter);
}

/**
 * MarkAllRead clears unread across the current view, pushing \Seen flags in
 * the background.
 */
export function MarkAllRead(filter: store$0.ListFilter): $CancellablePromise<void> {
    return $Call.ByID(1532381470, filter);
}

/**
 * MarkRead applies locally at once (snappy UI) and pushes the \Seen flag to
 * the server in the background; the next reconcile heals any failed push.
 */
export function MarkRead(messageID: number, read: boolean): $CancellablePromise<void> {
    return $Call.ByID(2773403271, messageID, read);
}

/**
 * SaveAttachment prompts for a location and writes the stored bytes. Returns
 * the chosen path, or "" when the user cancels.
 */
export function SaveAttachment(attachmentID: number): $CancellablePromise<string> {
    return $Call.ByID(1079976658, attachmentID);
}

/**
 * SearchContacts powers compose autocomplete: known correspondents matching
 * the typed fragment, best matches first.
 */
export function SearchContacts(query: string, limit: number): $CancellablePromise<store$0.Contact[] | null> {
    return $Call.ByID(824865675, query, limit);
}

/**
 * SetStarred applies locally at once and pushes \Flagged in the background.
 */
export function SetStarred(messageID: number, starred: boolean): $CancellablePromise<void> {
    return $Call.ByID(2135105713, messageID, starred);
}

/**
 * Snooze hides a message from lists until the wake time (local-only).
 */
export function Snooze(messageID: number, until: number): $CancellablePromise<void> {
    return $Call.ByID(1864749776, messageID, until);
}

/**
 * Trash moves a message into the account's trash folder on the server.
 */
export function Trash(messageID: number): $CancellablePromise<void> {
    return $Call.ByID(2569072960, messageID);
}

export function UnreadCounts(): $CancellablePromise<{ [_ in string]?: number } | null> {
    return $Call.ByID(3542151801);
}
