// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppSettings {
    "pollMinutes": number;
    "backfillDays": number;
}

/**
 * PickedFile is what the compose sheet shows for a chosen attachment; only
 * the path travels back on send.
 */
export interface PickedFile {
    "path": string;
    "name": string;
    "size": number;
}

/**
 * ResetOptions selects data categories for ResetData — coarse subjects, not
 * individual items.
 */
export interface ResetOptions {
    /**
     * Mailboxes removes every account, its credentials and all of its mail.
     */
    "mailboxes": boolean;

    /**
     * Mail wipes the downloaded message cache; accounts stay and re-sync.
     */
    "mail": boolean;

    /**
     * Drafts deletes all drafts, server-side too (best effort).
     */
    "drafts": boolean;

    /**
     * AICache clears cached summaries, digests and triage labels.
     */
    "aiCache": boolean;

    /**
     * Preferences clears the settings KV (name, sync & AI config) and the
     * AI API key.
     */
    "preferences": boolean;
}
