// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppSettings {
    "pollMinutes": number;
    "backfillDays": number;
}

/**
 * PickedFile is what the compose sheet shows for a chosen attachment; only
 * the path travels back on send.
 */
export interface PickedFile {
    "path": string;
    "name": string;
    "size": number;
}
