// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SendService covers composing: SMTP send, server-side drafts, and the
 * attachment picker.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mail$0 from "./internal/mail/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteDraft(messageID: number): $CancellablePromise<void> {
    return $Call.ByID(2707747735, messageID);
}

/**
 * PickAttachments opens the native multi-select file dialog.
 */
export function PickAttachments(): $CancellablePromise<$models.PickedFile[] | null> {
    return $Call.ByID(479029020);
}

export function SaveDraft(out: mail$0.Outgoing, replaceID: number): $CancellablePromise<number> {
    return $Call.ByID(602128849, out, replaceID);
}

export function SendMessage(out: mail$0.Outgoing): $CancellablePromise<void> {
    return $Call.ByID(4256575816, out);
}
