// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService backs the settings dialog's Sync section. (AI settings go
 * through AIService, accounts through AccountService, appearance is
 * frontend-local.)
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAppSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(498504974);
}

/**
 * GetUserName returns the person's name ("" until set).
 */
export function GetUserName(): $CancellablePromise<string> {
    return $Call.ByID(1942020304);
}

/**
 * SetAppSettings persists the sync tunables and restarts the engine so they
 * take effect immediately.
 */
export function SetAppSettings(settings: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(1738674778, settings);
}

/**
 * SetUserName stores the person's name for sign-offs and greetings.
 */
export function SetUserName(name: string): $CancellablePromise<void> {
    return $Call.ByID(2462812660, name);
}
