// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SyncService owns the IMAP sync engine. The engine starts only after the
 * window is revealed (never during boot) and follows account changes.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Restart rebuilds the engine, picking up new settings or a swapped store.
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(1153129541);
}

/**
 * SyncNow runs one incremental pass over every account (palette "Sync now").
 */
export function SyncNow(): $CancellablePromise<void> {
    return $Call.ByID(4106994651);
}
