// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TransferService implements the palette's Export/Import Data commands: a
 * portable zip holding a consistent database snapshot plus a manifest.
 * Secrets never leave the keychain — imported accounts on another machine
 * prompt for their passwords again.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Export prompts for a destination and writes the archive. Returns the path,
 * or "" when the user cancels.
 */
export function Export(): $CancellablePromise<string> {
    return $Call.ByID(3470037136);
}

/**
 * Import prompts for an archive, swaps the database in (backing up the old
 * one), and restarts the sync engine. Returns "" when the user cancels.
 */
export function Import(): $CancellablePromise<string> {
    return $Call.ByID(4116825615);
}

/**
 * ResetData deletes the selected categories. The frontend reloads afterwards,
 * so no change events are emitted here.
 */
export function ResetData(options: $models.ResetOptions): $CancellablePromise<void> {
    return $Call.ByID(464625957, options);
}
