// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AddInput carries everything the add-mailbox dialog collects. Username
 * defaults to Email when empty.
 */
export interface AddInput {
    "displayName": string;
    "email": string;
    "color": string;
    "imapHost": string;
    "imapPort": number;
    "smtpHost": string;
    "smtpPort": number;
    "username": string;
    "password": string;
}

/**
 * UpdateInput edits the user-tweakable fields; empty Password keeps the
 * existing credential.
 */
export interface UpdateInput {
    "id": string;
    "displayName": string;
    "color": string;
    "password": string;
}
