// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MailChanged fires after a folder's local mail changed; the frontend
 * refetches the affected views.
 */
export interface MailChanged {
    "accountId": string;
    "folderRole": string;
}

/**
 * SyncStatus reports per-account engine state: "syncing", "idle" or "error".
 */
export interface SyncStatus {
    "accountId": string;
    "state": string;
    "error": string;
}
