// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Account {
    "id": string;
    "email": string;
    "displayName": string;
    "color": string;
    "imapHost": string;
    "imapPort": number;
    "smtpHost": string;
    "smtpPort": number;
    "username": string;
    "authKind": string;
    "createdAt": number;
}
