// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Account {
    "id": string;
    "email": string;
    "displayName": string;
    "color": string;

    /**
     * Icon is a hugeicons export name ("" = show the initial letter).
     */
    "icon": string;
    "imapHost": string;
    "imapPort": number;
    "smtpHost": string;
    "smtpPort": number;
    "username": string;
    "authKind": string;
    "createdAt": number;
}

export interface Address {
    "name": string;
    "email": string;
}

export interface Attachment {
    "id": number;
    "messageId": number;
    "filename": string;
    "mimeType": string;
    "size": number;
    "contentId": string;
}

/**
 * Contact is a known correspondent, derived from synced mail — no separate
 * address book to maintain.
 */
export interface Contact {
    "email": string;
    "name": string;
}

/**
 * ListFilter selects a message list slice. Empty AccountID means the unified
 * view across every account.
 */
export interface ListFilter {
    "accountId": string;
    "folderRole": string;
    "limit": number;
    "offset": number;
}

export interface Message {
    "id": number;
    "accountId": string;
    "folderId": number;
    "uid": number;
    "messageId": string;
    "threadId": string;
    "subject": string;
    "from": Address;
    "to": Address[] | null;
    "cc": Address[] | null;
    "date": number;
    "snippet": string;
    "unread": boolean;
    "starred": boolean;
    "answered": boolean;
    "hasAttachments": boolean;
    "size": number;
    "snoozedUntil": number;
}

export interface MessageBody {
    "messageId": number;
    "textBody": string;
    "htmlSanitized": string;
}

/**
 * UnsubscribeCandidate is a sender worth reviewing: frequent, often unread,
 * ideally with a working unsubscribe link.
 */
export interface UnsubscribeCandidate {
    "fromEmail": string;
    "fromName": string;
    "count": number;
    "unreadCount": number;
    "lastDate": number;
    "unsubscribeUrl": string;
}
