// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BootService owns backend startup. Everything the app needs before first
 * paint happens in ServiceStartup — future: open SQLite + run migrations,
 * check keychain accounts, warm the local mail cache. The frontend splash
 * gates on this via IsBackendReady / the "backend:ready" event.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * IsBackendReady reports whether backend startup finished. The frontend calls
 * this before listening for "backend:ready" to avoid the missed-event race.
 */
export function IsBackendReady(): $CancellablePromise<boolean> {
    return $Call.ByID(907424186);
}
