// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActionItem is one extracted to-do.
 */
export interface ActionItem {
    "text": string;

    /**
     * Owner is who the item falls on ("you" for the account holder).
     */
    "owner": string;
}

/**
 * ComposeRequest is one turn of the compose conversation: fresh dictation,
 * or a revision of the draft the composer currently holds.
 */
export interface ComposeRequest {
    "accountId": string;
    "replyToMessageId": number;
    "instructions": string;

    /**
     * CurrentDraft is what's in the body right now ("" = start fresh).
     */
    "currentDraft": string;

    /**
     * PriorInstructions are earlier dictations for this draft, oldest first.
     */
    "priorInstructions": string[] | null;
}

/**
 * Config is the user-visible AI configuration (the key itself never leaves
 * the keychain — only whether one exists).
 */
export interface Config {
    "provider": string;
    "model": string;
    "hasKey": boolean;
    "listSummaries": boolean;
}

/**
 * PromptInfo is PromptDef plus the user's current override ("" = default).
 */
export interface PromptInfo {
    "id": string;
    "title": string;
    "description": string;

    /**
     * Placeholders substituted into the template at request time.
     */
    "placeholders": string[] | null;
    "default": string;
    "custom": string;
}

/**
 * StreamChunk is one event on the "ai:stream" channel. Seq orders chunks:
 * Wails dispatches each emitted event on its own goroutine, so back-to-back
 * emits can arrive out of order — the frontend reassembles by Seq.
 */
export interface StreamChunk {
    "requestId": string;
    "seq": number;
    "chunk": string;
    "done": boolean;
    "error": string;
}

/**
 * TriageResult labels one inbox message.
 */
export interface TriageResult {
    "messageId": number;

    /**
     * high | normal | low
     */
    "priority": string;
    "reason": string;
}
