// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActionItem is one extracted to-do.
 */
export interface ActionItem {
    "text": string;

    /**
     * Owner is who the item falls on ("you" for the account holder).
     */
    "owner": string;
}

/**
 * Config is the user-visible AI configuration (the key itself never leaves
 * the keychain — only whether one exists).
 */
export interface Config {
    "provider": string;
    "model": string;
    "hasKey": boolean;
    "listSummaries": boolean;
}

/**
 * StreamChunk is one event on the "ai:stream" channel. Seq orders chunks:
 * Wails dispatches each emitted event on its own goroutine, so back-to-back
 * emits can arrive out of order — the frontend reassembles by Seq.
 */
export interface StreamChunk {
    "requestId": string;
    "seq": number;
    "chunk": string;
    "done": boolean;
    "error": string;
}

/**
 * TriageResult labels one inbox message.
 */
export interface TriageResult {
    "messageId": number;

    /**
     * high | normal | low
     */
    "priority": string;
    "reason": string;
}
